blank_issues_enabled: true
contact_links:
  - name: Suggest idea
    url: https://github.com/jiacai2050/zigcli/discussions/categories/ideas
    about: Your valuable suggestions can help us improve and provide the best possible experience, please feel free to share your thoughts.
